-- 코드를 입력하세요
SELECT gu.USER_ID, gu.NICKNAME, SUM(gb.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD gb JOIN USED_GOODS_USER gu ON gu.USER_ID = gb.WRITER_ID
WHERE gb.STATUS = 'DONE'
GROUP BY gu.USER_ID HAVING SUM(gb.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC
