-- 코드를 입력하세요
SELECT DISTINCT cc.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR cc JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY rh ON cc.CAR_ID = rh.CAR_ID
WHERE cc.CAR_TYPE = '세단' AND START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY cc.CAR_ID DESC
