-- 코드를 입력하세요
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY, PRODUCT_NAME
HAVING MAX(PRICE) = (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT AS FP
    WHERE FP.CATEGORY = FOOD_PRODUCT.CATEGORY
)
ORDER BY MAX_PRICE DESC;
